const RESULT_PAGE = "/pages/result/result";
const CATALOG_VERSION = "2026.06.19-mvp2";

const cityMeta = {
  上海: {
    city: "上海",
    tripCityId: 2,
    locale: "ja-JP",
    currency: "JPY",
    countryCode: "CN",
  },
  东京: {
    city: "东京",
    tripCityId: 294,
    locale: "ja-JP",
    currency: "JPY",
    countryCode: "JP",
  },
  新加坡: {
    city: "新加坡",
    tripCityId: 53,
    locale: "ja-JP",
    currency: "JPY",
    countryCode: "SG",
  },
};

const cityAliases = {
  shanghai: "上海",
  上海市: "上海",
  魔都: "上海",
  tokyo: "东京",
  東京: "东京",
  东京市: "东京",
  singapore: "新加坡",
  sg: "新加坡",
  狮城: "新加坡",
  新加坡市: "新加坡",
};

const typeConfig = {
  family: {
    label: "亲子家庭",
    keywords: ["亲子", "家庭", "带娃", "小朋友", "孩子", "family"],
    dayThemes: ["轻松抵达与城市地标", "高转化主题乐园日", "亲子友好收尾"],
  },
  couple: {
    label: "情侣朋友",
    keywords: ["情侣", "约会", "浪漫", "couple", "朋友", "蜜月"],
    dayThemes: ["城市漫步与夜景", "沉浸式体验与热门展览", "慢节奏市集与观景"],
  },
  culture: {
    label: "文化探索",
    keywords: ["文化", "历史", "展览", "博物馆", "艺术", "citywalk", "culture"],
    dayThemes: ["历史街区与经典地标", "博物馆与城市观察", "本地街区与夜景"],
  },
  default: {
    label: "经典首次游",
    keywords: [],
    dayThemes: ["城市初印象与地标", "核心 POI 深度游", "轻松补充与购物"],
  },
};

const poiCatalog = {
  "shanghai-disney": {
    poi_id: "shanghai-disney",
    name: "上海迪士尼度假区",
    city: "上海",
    tags: ["亲子", "乐园", "高转化", "经典"],
    priority: 99,
    reason: "高转化亲子乐园，适合整天游玩，也最适合作为上海初访的成交入口。",
    image: "https://images.unsplash.com/photo-1567279683045-5cc011f77954?auto=format&fit=crop&w=900&q=80",
    audience: "带娃家庭、首次来沪用户",
    stay: "建议整日游玩",
    keyword: "上海迪士尼",
    ticketSkus: ["SHDR-1D"],
  },
  "shanghai-tower": {
    poi_id: "shanghai-tower",
    name: "上海中心大厦观光厅",
    city: "上海",
    tags: ["夜景", "地标", "高转化"],
    priority: 94,
    reason: "夜景成交稳定，适合和陆家嘴、外滩组成低决策成本的经典路线。",
    image: "https://images.unsplash.com/photo-1538428494232-9c0d8a3ab403?auto=format&fit=crop&w=900&q=80",
    audience: "情侣、城市观景人群",
    stay: "建议 2-3 小时",
    keyword: "上海中心 观景",
    ticketSkus: ["SHTOWER-118F"],
  },
  "yu-garden": {
    poi_id: "yu-garden",
    name: "豫园",
    city: "上海",
    tags: ["文化", "经典", "半日游"],
    priority: 86,
    reason: "历史文化感强，半日成团动线自然，适合轻量文化行程。",
    image: "https://images.unsplash.com/photo-1545893835-abaa50cbe628?auto=format&fit=crop&w=900&q=80",
    audience: "文化体验、首次来沪游客",
    stay: "建议 2 小时",
    keyword: "豫园 门票",
    ticketSkus: ["YUGARDEN-ENTRY"],
  },
  "tokyo-disneysea": {
    poi_id: "tokyo-disneysea",
    name: "东京迪士尼海洋",
    city: "东京",
    tags: ["亲子", "乐园", "高转化"],
    priority: 98,
    reason: "东京最强门票转化场景之一，适合单独安排整日行程，购买决策明确。",
    image: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=900&q=80",
    audience: "情侣、亲子、迪士尼粉丝",
    stay: "建议整日游玩",
    keyword: "東京ディズニーシー",
    ticketSkus: ["TDS-1D"],
  },
  "teamlab-planets": {
    poi_id: "teamlab-planets",
    name: "teamLab Planets TOKYO",
    city: "东京",
    tags: ["展览", "情侣", "高转化"],
    priority: 93,
    reason: "沉浸式体验强，内容种草能力高，适合情侣和朋友出行。",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=900&q=80",
    audience: "年轻情侣、朋友、内容种草用户",
    stay: "建议 1.5-2 小时",
    keyword: "teamLab Planets TOKYO",
    ticketSkus: ["TEAMLAB-PLANETS"],
  },
  skytree: {
    poi_id: "skytree",
    name: "东京晴空塔",
    city: "东京",
    tags: ["夜景", "地标", "经典"],
    priority: 88,
    reason: "城市地标转化稳定，适合搭配浅草和隅田川一线游玩。",
    image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=900&q=80",
    audience: "首次东京行、夜景偏好用户",
    stay: "建议 2 小时",
    keyword: "東京スカイツリー",
    ticketSkus: ["SKYTREE-DECK"],
  },
  sentosa: {
    poi_id: "sentosa",
    name: "圣淘沙名胜世界",
    city: "新加坡",
    tags: ["亲子", "乐园", "高转化"],
    priority: 97,
    reason: "新加坡门票分销主战场，景区聚合度高，方便承接多类亲子需求。",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=900&q=80",
    audience: "亲子、朋友、综合乐园需求",
    stay: "建议整日游玩",
    keyword: "圣淘沙 环球影城",
    ticketSkus: ["USS-1D"],
  },
  "gardens-by-the-bay": {
    poi_id: "gardens-by-the-bay",
    name: "滨海湾花园",
    city: "新加坡",
    tags: ["地标", "自然", "夜景"],
    priority: 92,
    reason: "白天温室、夜间灯光秀都有承接能力，适合多数行程模板。",
    image: "https://images.unsplash.com/photo-1496939376851-89342e90adcd?auto=format&fit=crop&w=900&q=80",
    audience: "首次来新游客、夜景偏好用户",
    stay: "建议 2-4 小时",
    keyword: "滨海湾花园",
    ticketSkus: ["GBB-DOME"],
  },
  "singapore-zoo": {
    poi_id: "singapore-zoo",
    name: "新加坡动物园",
    city: "新加坡",
    tags: ["亲子", "自然", "高转化"],
    priority: 89,
    reason: "亲子稳定成交景点，也方便扩展夜间动物园等联票场景。",
    image: "https://images.unsplash.com/photo-1570288685280-7802a8f8c4fa?auto=format&fit=crop&w=900&q=80",
    audience: "亲子家庭、自然体验用户",
    stay: "建议半日游",
    keyword: "新加坡动物园",
    ticketSkus: ["SGZOO-ENTRY"],
  },
};

const ticketCatalog = {
  "SHDR-1D": {
    sku: "SHDR-1D",
    poi_id: "shanghai-disney",
    title: "上海迪士尼 1 日标准票",
    price: 475,
    originalPrice: 599,
    currency: "CNY",
    benefits: ["热门亲子乐园", "建议提前预订", "整日游动线清晰"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 98,
    bookingNote: "热门日期建议提前 3-7 天查看 Trip 最新页面。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "带娃家庭、首次来沪用户",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/shanghai/shanghai-disney-resort-13412802/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "SHTOWER-118F": {
    sku: "SHTOWER-118F",
    poi_id: "shanghai-tower",
    title: "上海中心 118 层观光厅门票",
    price: 180,
    originalPrice: 220,
    currency: "CNY",
    benefits: ["高空夜景", "陆家嘴顺路", "2 小时可完成"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 93,
    bookingNote: "日落时段热度较高，建议在详情页确认可预约时段。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "情侣、城市观景人群",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/shanghai/top-of-shanghai-observatory-30745956?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "YUGARDEN-ENTRY": {
    sku: "YUGARDEN-ENTRY",
    poi_id: "yu-garden",
    title: "豫园成人票",
    price: 40,
    originalPrice: 45,
    currency: "CNY",
    benefits: ["轻量文化行程", "可搭配城隍庙", "半日可完成"],
    ticketStatus: "limited",
    cta: "去 Trip 预订",
    conversionScore: 82,
    bookingNote: "节假日和夜游场次以 Trip 页面实际可订状态为准。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "文化体验、首次来沪游客",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/shanghai/yu-garden-75615/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "TDS-1D": {
    sku: "TDS-1D",
    poi_id: "tokyo-disneysea",
    title: "东京迪士尼海洋 1 日护照",
    price: 498,
    originalPrice: 560,
    currency: "CNY",
    benefits: ["高转化乐园", "整日游安排", "适合情侣与亲子"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 99,
    bookingNote: "热门日期波动明显，请以 Trip 页面实时价格与可订状态为准。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "情侣、亲子、迪士尼粉丝",
    detailUrl: "https://jp.trip.com/things-to-do/experiences/tokyo?productId=44938465&currency=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "TEAMLAB-PLANETS": {
    sku: "TEAMLAB-PLANETS",
    poi_id: "teamlab-planets",
    title: "teamLab Planets TOKYO 入场券",
    price: 198,
    originalPrice: 236,
    currency: "CNY",
    benefits: ["沉浸式展览", "内容种草强", "适合半日游"],
    ticketStatus: "limited",
    cta: "去 Trip 预订",
    conversionScore: 94,
    bookingNote: "限时预约型产品较多，建议优先查看 Trip 页面可订时间。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "年轻情侣、朋友、内容种草用户",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/tokyo/teamlab-planets-tokyo-61909015/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "SKYTREE-DECK": {
    sku: "SKYTREE-DECK",
    poi_id: "skytree",
    title: "东京晴空塔天望甲板门票",
    price: 132,
    originalPrice: 160,
    currency: "CNY",
    benefits: ["城市观景", "夜景友好", "适合首次东京行"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 87,
    bookingNote: "天气和日落时段会影响体验，建议查看 Trip 最新说明。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "首次东京行、夜景偏好用户",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/tokyo/tokyo-skytree-91422/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "USS-1D": {
    sku: "USS-1D",
    poi_id: "sentosa",
    title: "新加坡环球影城 1 日票",
    price: 438,
    originalPrice: 520,
    currency: "CNY",
    benefits: ["圣淘沙核心", "电子票友好", "适合整日安排"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 98,
    bookingNote: "假日高峰建议优先查看 Trip 实时门票页。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "亲子、朋友、综合乐园需求",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/singapore/universal-studios-singapore-89732/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "GBB-DOME": {
    sku: "GBB-DOME",
    poi_id: "gardens-by-the-bay",
    title: "滨海湾花园双馆门票",
    price: 168,
    originalPrice: 199,
    currency: "CNY",
    benefits: ["双馆套票", "白天夜晚都可玩", "适合多数客群"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 91,
    bookingNote: "夜间灯光秀不一定需要门票，具体场馆以 Trip 页面说明为准。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "首次来新游客、夜景偏好用户",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/singapore/gardens-by-the-bay-94795/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
  "SGZOO-ENTRY": {
    sku: "SGZOO-ENTRY",
    poi_id: "singapore-zoo",
    title: "新加坡动物园门票",
    price: 238,
    originalPrice: 280,
    currency: "CNY",
    benefits: ["亲子强需求", "半日游可行", "可扩展联票"],
    ticketStatus: "available",
    cta: "去 Trip 预订",
    conversionScore: 88,
    bookingNote: "联票和单票均可能出现，请以 Trip 页实际售卖产品为准。",
    priceUpdatedAt: "2026-06-19 10:00",
    suitableFor: "亲子家庭、自然体验用户",
    detailUrl: "https://jp.trip.com/travel-guide/attraction/singapore/singapore-zoo-76136/?curr=JPY&locale=ja-JP",
    miniProgram: null,
    catalogVersion: CATALOG_VERSION,
  },
};

const purchaseRules = {
  provider: "Trip",
  tripDomain: "https://jp.trip.com",
  tripHomeUrl: "https://jp.trip.com/things-to-do/?locale=ja_jp&curr=JPY",
  defaultLocale: "ja-JP",
  defaultCurrency: "JPY",
  cityQuery: {
    citytype: "dt",
    pagetype: "city",
    pshowcode: "1daytrip",
  },
  defaultButtonText: "去 Trip 预订",
  modePriority: ["miniProgram", "webViewDetail", "webViewKeyword", "webViewCity", "disabled"],
};

function getCatalogSnapshot() {
  return {
    cityMeta,
    poiCatalog,
    ticketCatalog,
    purchaseRules,
  };
}

module.exports = {
  RESULT_PAGE,
  CATALOG_VERSION,
  cityMeta,
  cityAliases,
  typeConfig,
  poiCatalog,
  ticketCatalog,
  purchaseRules,
  getCatalogSnapshot,
};
